version: '3'
services:

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    container_name: zookeeper
    network_mode: bridge
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    container_name: kafka
    network_mode: bridge
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: 'postgres:9.6-alpine'
    container_name: postgres
    network_mode: bridge
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak:11.0.0
    container_name: keycloak
    network_mode: bridge
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - grafana
      - prometheus
      - jaeger
      - kafka
      - zookeeper
      - contas
      - analise
      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
    restart: on-failure

  analise:
    image: 'zupacademy/analise-financeira'
    container_name: analise
    network_mode: bridge
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  contas:
    image: 'zupacademy/contas'
    container_name: contas
    network_mode: bridge
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  transacoes:
    image: 'zupacademy/transacoes'
    container_name: transacoes
    network_mode: bridge
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    container_name: jaeger
    network_mode: bridge
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    network_mode: bridge
    volumes:
      #  - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/etc/prometheus/
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:7.3.4
    container_name: grafana
    network_mode: bridge
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  vault:
    image: vault:1.5.3
    container_name: vault
    network_mode: bridge
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_ADDR: http://127.0.0.1:8200

  proposta:
    image: edsonmoreirajr/proposta:latest
    container_name: proposta
    ports:
      - "8080:8080"
    depends_on:
      - mysql_proposta
    environment:
      - DATABASE_HOST=mysql_proposta

  mysql_proposta:
    image: mysql:8.0.22
    container_name: mysql_proposta
    environment:
      MYSQL_ROOT_PASSWORD: MySql2020@
      MYSQL_DATABASE: proposta
    ports:
      - 3306:3306
    volumes:
      - mysql-proposta:\var\lib\mysql

  mysql_transacao:
    image: mysql:8.0.22
    container_name: mysql_transacao
    environment:
      MYSQL_ROOT_PASSWORD: MySql2020@
      MYSQL_DATABASE: transacao
    ports:
      - 3307:3306
    volumes:
      - mysql-transacao:\var\lib\mysql

  mysql_fatura:
    image: mysql:8.0.22
    container_name: mysql_fatura
    environment:
      MYSQL_ROOT_PASSWORD: MySql2020@
      MYSQL_DATABASE: fatura
    ports:
      - 3308:3306
    volumes:
      - mysql-fatura:\var\lib\mysql

volumes:
  grafana-volume:
  prometheus-volume:
  postgres-volume:
  mysql-proposta:
  mysql-transacao:
  mysql-fatura: